### ISSUE TITLE
Custom command execution

### ISSUE THREAD

**Issue by jorisvos** [mineplugs/mineplug-core#1]
When you do /mp (or /stats) the command works. But since we use our own CommandHandling system we cannot return true or false (because we don't use the default command executor) and thus the command is shown before the command is executed.

See the image, I do /stats and see my stats but also /stats <player> (which is in the plugin.yml). The same goes for /mp

<img width="966" alt="image" src="https://user-images.githubusercontent.com/26248126/56805311-ef0b8180-6828-11e9-80d0-fffc5d93e734.png">

**Comment by SMWLucasO** [comment]
Could possibly be due to a missing `setEventCancelled(true)` in the listener, though we should first verify that the command is actually ours.

**Comment by SMWLucasO** [comment]
> Could possibly be due to a missing `setEventCancelled(true)` in the listener, though we should first verify that the command is actually ours.

this can be done inside of the `null != template` logical statement.

**Comment by jorisvos** [comment]
@SMWLucasO check the statistics branch. Just created. Also fixes this issue

**Comment by SMWLucasO** [comment]
Issue has been solved.
